repos:
  # - repo: https://github.com/psf/black
  #   rev: 23.7.0
  #   hooks:
  #     - id: black
  #       args: ["qlib", "-l 120"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
            "--rcfile=.pylintrc", # 指定配置文件
            "--msg-template='{abspath}:{line} :{column}: {msg_id}: {msg} {symbol}'", # 指定输出格式
            "--ignore=.venv", # 指定忽略文件或目录
          ]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--ignore=E501,F541,E266,E402,W503,E731,E203"]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: ["--line-length=120"]
